runtime: nodejs
env: flex
env_variables:
  SQL_USER: root
  SQL_PASSWORD: SApper81*!
  SQL_DATABASE: daimoniondb
  INSTANCE_CONNECTION_NAME: crested-return-227514:europe-north1:daimonion
beta_settings:
  cloud_sql_instances: crested-return-227514:europe-north1:daimonion